apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  logs.region: us-east-1
  cluster.name: my-cluster
  http.server: "On"
  http.port: "2020"
  read.head: "Off"
  read.tail: "On"